# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.AllocatorStats do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :directArenas,
    :heapArenas,
    :normalCacheSize,
    :numDirectArenas,
    :numHeapArenas,
    :numThreadLocalCaches,
    :smallCacheSize
  ]

  @type t :: %__MODULE__{
    :directArenas => [PulsarAdmin.Model.PoolArenaStats.t] | nil,
    :heapArenas => [PulsarAdmin.Model.PoolArenaStats.t] | nil,
    :normalCacheSize => integer() | nil,
    :numDirectArenas => integer() | nil,
    :numHeapArenas => integer() | nil,
    :numThreadLocalCaches => integer() | nil,
    :smallCacheSize => integer() | nil
  }

  alias PulsarAdmin.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:directArenas, :list, PulsarAdmin.Model.PoolArenaStats)
     |> Deserializer.deserialize(:heapArenas, :list, PulsarAdmin.Model.PoolArenaStats)
  end
end

