# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.AuthenticationParameters do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :clientAuthenticationDataSource,
    :clientRole,
    :originalPrincipal
  ]

  @type t :: %__MODULE__{
    :clientAuthenticationDataSource => PulsarAdmin.Model.AuthenticationDataSource.t | nil,
    :clientRole => String.t | nil,
    :originalPrincipal => String.t | nil
  }

  alias PulsarAdmin.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:clientAuthenticationDataSource, :struct, PulsarAdmin.Model.AuthenticationDataSource)
  end
end

