# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.AuthenticationDataSource do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :commandData,
    :httpAuthType,
    :peerAddress,
    :subscription,
    :tlsCertificates
  ]

  @type t :: %__MODULE__{
    :commandData => String.t | nil,
    :httpAuthType => String.t | nil,
    :peerAddress => map() | nil,
    :subscription => String.t | nil,
    :tlsCertificates => [PulsarAdmin.Model.Certificate.t] | nil
  }

  alias PulsarAdmin.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:tlsCertificates, :list, PulsarAdmin.Model.Certificate)
  end
end

