# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.AuthPolicies do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :namespaceAuthentication,
    :subscriptionAuthentication,
    :topicAuthentication
  ]

  @type t :: %__MODULE__{
    :namespaceAuthentication => %{optional(String.t) => [String.t]} | nil,
    :subscriptionAuthentication => %{optional(String.t) => [String.t]} | nil,
    :topicAuthentication => %{optional(String.t) => %{optional(String.t) => [String.t]}} | nil
  }

  alias PulsarAdmin.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:namespaceAuthentication, :map, PulsarAdmin.Model.Set)
     |> Deserializer.deserialize(:subscriptionAuthentication, :map, PulsarAdmin.Model.Set)
  end
end

