# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.AutoTopicCreationOverrideImpl do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :allowAutoTopicCreation,
    :defaultNumPartitions,
    :topicType
  ]

  @type t :: %__MODULE__{
    :allowAutoTopicCreation => boolean() | nil,
    :defaultNumPartitions => integer() | nil,
    :topicType => String.t | nil
  }

  def decode(value) do
    value
  end
end

