# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.AutoFailoverPolicyData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :parameters,
    :policyType
  ]

  @type t :: %__MODULE__{
    :parameters => %{optional(String.t) => String.t} | nil,
    :policyType => String.t | nil
  }

  def decode(value) do
    value
  end
end

