# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.BacklogQuota do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :limit,
    :limitSize,
    :limitTime,
    :policy
  ]

  @type t :: %__MODULE__{
    :limit => integer() | nil,
    :limitSize => integer() | nil,
    :limitTime => integer() | nil,
    :policy => String.t | nil
  }

  def decode(value) do
    value
  end
end

