# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.BitSet do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :empty
  ]

  @type t :: %__MODULE__{
    :empty => boolean() | nil
  }

  def decode(value) do
    value
  end
end

