# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.BookieInfo do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :hostname,
    :rack
  ]

  @type t :: %__MODULE__{
    :hostname => String.t | nil,
    :rack => String.t | nil
  }

  def decode(value) do
    value
  end
end

