# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.BookiesClusterInfo do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :bookies
  ]

  @type t :: %__MODULE__{
    :bookies => [PulsarAdmin.Model.RawBookieInfo.t] | nil
  }

  alias PulsarAdmin.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:bookies, :list, PulsarAdmin.Model.RawBookieInfo)
  end
end

