# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.BrokerNamespaceIsolationData do
  @moduledoc """
  The namespace isolation data for a given broker
  """

  @derive Jason.Encoder
  defstruct [
    :brokerName,
    :namespaceRegex,
    :policyName,
    :primary
  ]

  @type t :: %__MODULE__{
    :brokerName => String.t | nil,
    :namespaceRegex => [String.t] | nil,
    :policyName => String.t | nil,
    :primary => boolean() | nil
  }

  def decode(value) do
    value
  end
end

