# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.BundlesData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :boundaries,
    :numBundles
  ]

  @type t :: %__MODULE__{
    :boundaries => [String.t] | nil,
    :numBundles => integer() | nil
  }

  def decode(value) do
    value
  end
end

