# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.Certificate do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :encoded,
    :publicKey,
    :type
  ]

  @type t :: %__MODULE__{
    :encoded => [binary()] | nil,
    :publicKey => PulsarAdmin.Model.PublicKey.t | nil,
    :type => String.t | nil
  }

  alias PulsarAdmin.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:publicKey, :struct, PulsarAdmin.Model.PublicKey)
  end
end

