# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.ConnectorDefinition do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :description,
    :name,
    :sinkClass,
    :sinkConfigClass,
    :sourceClass,
    :sourceConfigClass
  ]

  @type t :: %__MODULE__{
    :description => String.t | nil,
    :name => String.t | nil,
    :sinkClass => String.t | nil,
    :sinkConfigClass => String.t | nil,
    :sourceClass => String.t | nil,
    :sourceConfigClass => String.t | nil
  }

  def decode(value) do
    value
  end
end

