# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.ConsumerStats do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :address,
    :availablePermits,
    :avgMessagesPerEntry,
    :blockedConsumerOnUnackedMsgs,
    :bytesOutCounter,
    :chunkedMessageRate,
    :clientVersion,
    :connectedSince,
    :consumerName,
    :keyHashRanges,
    :lastAckedTimestamp,
    :lastConsumedFlowTimestamp,
    :lastConsumedTimestamp,
    :messageAckRate,
    :metadata,
    :msgOutCounter,
    :msgRateOut,
    :msgRateRedeliver,
    :msgThroughputOut,
    :readPositionWhenJoining,
    :unackedMessages
  ]

  @type t :: %__MODULE__{
    :address => String.t | nil,
    :availablePermits => integer() | nil,
    :avgMessagesPerEntry => integer() | nil,
    :blockedConsumerOnUnackedMsgs => boolean() | nil,
    :bytesOutCounter => integer() | nil,
    :chunkedMessageRate => float() | nil,
    :clientVersion => String.t | nil,
    :connectedSince => String.t | nil,
    :consumerName => String.t | nil,
    :keyHashRanges => [String.t] | nil,
    :lastAckedTimestamp => integer() | nil,
    :lastConsumedFlowTimestamp => integer() | nil,
    :lastConsumedTimestamp => integer() | nil,
    :messageAckRate => float() | nil,
    :metadata => %{optional(String.t) => String.t} | nil,
    :msgOutCounter => integer() | nil,
    :msgRateOut => float() | nil,
    :msgRateRedeliver => float() | nil,
    :msgThroughputOut => float() | nil,
    :readPositionWhenJoining => String.t | nil,
    :unackedMessages => integer() | nil
  }

  def decode(value) do
    value
  end
end

