# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.CursorDetails do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :cursorBacklog,
    :cursorLedgerId
  ]

  @type t :: %__MODULE__{
    :cursorBacklog => integer() | nil,
    :cursorLedgerId => integer() | nil
  }

  def decode(value) do
    value
  end
end

