# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.CursorStats do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :active,
    :cursorLedger,
    :cursorLedgerLastEntry,
    :individuallyDeletedMessages,
    :lastLedgerSwitchTimestamp,
    :markDeletePosition,
    :messagesConsumedCounter,
    :numberOfEntriesSinceFirstNotAckedMessage,
    :pendingReadOps,
    :properties,
    :readPosition,
    :state,
    :subscriptionHavePendingRead,
    :subscriptionHavePendingReplayRead,
    :totalNonContiguousDeletedMessagesRange,
    :waitingReadOp
  ]

  @type t :: %__MODULE__{
    :active => boolean() | nil,
    :cursorLedger => integer() | nil,
    :cursorLedgerLastEntry => integer() | nil,
    :individuallyDeletedMessages => String.t | nil,
    :lastLedgerSwitchTimestamp => String.t | nil,
    :markDeletePosition => String.t | nil,
    :messagesConsumedCounter => integer() | nil,
    :numberOfEntriesSinceFirstNotAckedMessage => integer() | nil,
    :pendingReadOps => integer() | nil,
    :properties => %{optional(String.t) => integer()} | nil,
    :readPosition => String.t | nil,
    :state => String.t | nil,
    :subscriptionHavePendingRead => boolean() | nil,
    :subscriptionHavePendingReplayRead => boolean() | nil,
    :totalNonContiguousDeletedMessagesRange => integer() | nil,
    :waitingReadOp => boolean() | nil
  }

  def decode(value) do
    value
  end
end

