# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.DeleteSchemaResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :version
  ]

  @type t :: %__MODULE__{
    :version => integer() | nil
  }

  def decode(value) do
    value
  end
end

