# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.DispatchRateImpl do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :dispatchThrottlingRateInByte,
    :dispatchThrottlingRateInMsg,
    :ratePeriodInSecond,
    :relativeToPublishRate
  ]

  @type t :: %__MODULE__{
    :dispatchThrottlingRateInByte => integer() | nil,
    :dispatchThrottlingRateInMsg => integer() | nil,
    :ratePeriodInSecond => integer() | nil,
    :relativeToPublishRate => boolean() | nil
  }

  def decode(value) do
    value
  end
end

