# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.FunctionInstanceStatsDataBase do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :avgProcessLatency,
    :processedSuccessfullyTotal,
    :receivedTotal,
    :systemExceptionsTotal,
    :userExceptionsTotal
  ]

  @type t :: %__MODULE__{
    :avgProcessLatency => float() | nil,
    :processedSuccessfullyTotal => integer() | nil,
    :receivedTotal => integer() | nil,
    :systemExceptionsTotal => integer() | nil,
    :userExceptionsTotal => integer() | nil
  }

  def decode(value) do
    value
  end
end

