# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.GetSchemaResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :data,
    :properties,
    :timestamp,
    :type,
    :version
  ]

  @type t :: %__MODULE__{
    :data => String.t | nil,
    :properties => %{optional(String.t) => String.t} | nil,
    :timestamp => integer() | nil,
    :type => String.t | nil,
    :version => integer() | nil
  }

  def decode(value) do
    value
  end
end

