# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.GetAllVersionsSchemaResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :getSchemaResponses
  ]

  @type t :: %__MODULE__{
    :getSchemaResponses => [PulsarAdmin.Model.GetSchemaResponse.t] | nil
  }

  alias PulsarAdmin.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:getSchemaResponses, :list, PulsarAdmin.Model.GetSchemaResponse)
  end
end

