# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.InternalConfigurationData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :bookkeeperMetadataServiceUri,
    :configurationMetadataStoreUrl,
    :configurationStoreServers,
    :ledgersRootPath,
    :metadataStoreUrl,
    :stateStorageServiceUrl,
    :zookeeperServers
  ]

  @type t :: %__MODULE__{
    :bookkeeperMetadataServiceUri => String.t | nil,
    :configurationMetadataStoreUrl => String.t | nil,
    :configurationStoreServers => String.t | nil,
    :ledgersRootPath => String.t | nil,
    :metadataStoreUrl => String.t | nil,
    :stateStorageServiceUrl => String.t | nil,
    :zookeeperServers => String.t | nil
  }

  def decode(value) do
    value
  end
end

