# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.IsCompatibilityResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :compatibility,
    :schemaCompatibilityStrategy
  ]

  @type t :: %__MODULE__{
    :compatibility => boolean() | nil,
    :schemaCompatibilityStrategy => String.t | nil
  }

  def decode(value) do
    value
  end
end

