# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.KubernetesContainerFactory do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :changeConfigMap,
    :changeConfigMapNamespace,
    :configAdminCLI,
    :cpuOverCommitRatio,
    :customLabels,
    :expectedMetricsCollectionInterval,
    :extraFunctionDependenciesDir,
    :functionDockerImages,
    :functionInstanceClassPath,
    :gracePeriodSeconds,
    :grpcPort,
    :imagePullPolicy,
    :installUserCodeDependencies,
    :jobName,
    :jobNamespace,
    :k8Uri,
    :kubernetesFunctionAuthProviderConfig,
    :memoryOverCommitRatio,
    :metricsPort,
    :narExtractionDirectory,
    :percentMemoryPadding,
    :pulsarAdminUrl,
    :pulsarDockerImageName,
    :pulsarRootDir,
    :pulsarServiceUrl,
    :pythonDependencyRepository,
    :pythonExtraDependencyRepository,
    :submittingInsidePod
  ]

  @type t :: %__MODULE__{
    :changeConfigMap => String.t | nil,
    :changeConfigMapNamespace => String.t | nil,
    :configAdminCLI => String.t | nil,
    :cpuOverCommitRatio => float() | nil,
    :customLabels => %{optional(String.t) => String.t} | nil,
    :expectedMetricsCollectionInterval => integer() | nil,
    :extraFunctionDependenciesDir => String.t | nil,
    :functionDockerImages => %{optional(String.t) => String.t} | nil,
    :functionInstanceClassPath => String.t | nil,
    :gracePeriodSeconds => integer() | nil,
    :grpcPort => integer() | nil,
    :imagePullPolicy => String.t | nil,
    :installUserCodeDependencies => boolean() | nil,
    :jobName => String.t | nil,
    :jobNamespace => String.t | nil,
    :k8Uri => String.t | nil,
    :kubernetesFunctionAuthProviderConfig => %{optional(String.t) => map()} | nil,
    :memoryOverCommitRatio => float() | nil,
    :metricsPort => integer() | nil,
    :narExtractionDirectory => String.t | nil,
    :percentMemoryPadding => integer() | nil,
    :pulsarAdminUrl => String.t | nil,
    :pulsarDockerImageName => String.t | nil,
    :pulsarRootDir => String.t | nil,
    :pulsarServiceUrl => String.t | nil,
    :pythonDependencyRepository => String.t | nil,
    :pythonExtraDependencyRepository => String.t | nil,
    :submittingInsidePod => boolean() | nil
  }

  def decode(value) do
    value
  end
end

