# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.LedgerInfo do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :entries,
    :isOffloaded,
    :ledgerId,
    :offloadedContextUuid,
    :size,
    :timestamp
  ]

  @type t :: %__MODULE__{
    :entries => integer() | nil,
    :isOffloaded => boolean() | nil,
    :ledgerId => integer() | nil,
    :offloadedContextUuid => String.t | nil,
    :size => integer() | nil,
    :timestamp => integer() | nil
  }

  def decode(value) do
    value
  end
end

