# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.ManagedLedgerInfo do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :creationDate,
    :cursors,
    :ledgers,
    :modificationDate,
    :properties,
    :terminatedPosition,
    :version
  ]

  @type t :: %__MODULE__{
    :creationDate => String.t | nil,
    :cursors => %{optional(String.t) => PulsarAdmin.Model.CursorInfo.t} | nil,
    :ledgers => [PulsarAdmin.Model.LedgerInfo.t] | nil,
    :modificationDate => String.t | nil,
    :properties => %{optional(String.t) => String.t} | nil,
    :terminatedPosition => PulsarAdmin.Model.PositionInfo.t | nil,
    :version => integer() | nil
  }

  alias PulsarAdmin.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:cursors, :map, PulsarAdmin.Model.CursorInfo)
     |> Deserializer.deserialize(:ledgers, :list, PulsarAdmin.Model.LedgerInfo)
     |> Deserializer.deserialize(:terminatedPosition, :struct, PulsarAdmin.Model.PositionInfo)
  end
end

