# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.MessageRangeInfo do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :from,
    :to
  ]

  @type t :: %__MODULE__{
    :from => PulsarAdmin.Model.PositionInfo.t | nil,
    :to => PulsarAdmin.Model.PositionInfo.t | nil
  }

  alias PulsarAdmin.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:from, :struct, PulsarAdmin.Model.PositionInfo)
     |> Deserializer.deserialize(:to, :struct, PulsarAdmin.Model.PositionInfo)
  end
end

