# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.Metrics do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :dimensions,
    :metrics
  ]

  @type t :: %__MODULE__{
    :dimensions => %{optional(String.t) => String.t} | nil,
    :metrics => %{optional(String.t) => map()} | nil
  }

  def decode(value) do
    value
  end
end

