# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.NamespaceBundleStats do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :cacheSize,
    :consumerCount,
    :msgRateIn,
    :msgRateOut,
    :msgThroughputIn,
    :msgThroughputOut,
    :producerCount,
    :topics
  ]

  @type t :: %__MODULE__{
    :cacheSize => integer() | nil,
    :consumerCount => integer() | nil,
    :msgRateIn => float() | nil,
    :msgRateOut => float() | nil,
    :msgThroughputIn => float() | nil,
    :msgThroughputOut => float() | nil,
    :producerCount => integer() | nil,
    :topics => integer() | nil
  }

  def decode(value) do
    value
  end
end

