# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.NamespaceIsolationData do
  @moduledoc """
  The data of namespace isolation configuration
  """

  @derive Jason.Encoder
  defstruct [
    :auto_failover_policy,
    :namespaces,
    :primary,
    :secondary
  ]

  @type t :: %__MODULE__{
    :auto_failover_policy => PulsarAdmin.Model.AutoFailoverPolicyData.t | nil,
    :namespaces => [String.t] | nil,
    :primary => [String.t] | nil,
    :secondary => [String.t] | nil
  }

  alias PulsarAdmin.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:auto_failover_policy, :struct, PulsarAdmin.Model.AutoFailoverPolicyData)
  end
end

