# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.NamespaceOwnershipStatus do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :broker_assignment,
    :is_active,
    :is_controlled
  ]

  @type t :: %__MODULE__{
    :broker_assignment => String.t | nil,
    :is_active => boolean() | nil,
    :is_controlled => boolean() | nil
  }

  def decode(value) do
    value
  end
end

