# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.OffloadProcessStatus do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :firstUnoffloadedMessage,
    :lastError,
    :status
  ]

  @type t :: %__MODULE__{
    :firstUnoffloadedMessage => map() | nil,
    :lastError => String.t | nil,
    :status => String.t | nil
  }

  def decode(value) do
    value
  end
end

