# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.PartitionedTopicMetadata do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :deleted,
    :partitions,
    :properties
  ]

  @type t :: %__MODULE__{
    :deleted => boolean() | nil,
    :partitions => integer() | nil,
    :properties => %{optional(String.t) => String.t} | nil
  }

  def decode(value) do
    value
  end
end

