# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.PartitionedTopicInternalStats do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :metadata,
    :partitions
  ]

  @type t :: %__MODULE__{
    :metadata => PulsarAdmin.Model.PartitionedTopicMetadata.t | nil,
    :partitions => %{optional(String.t) => PulsarAdmin.Model.PersistentTopicInternalStats.t} | nil
  }

  alias PulsarAdmin.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:metadata, :struct, PulsarAdmin.Model.PartitionedTopicMetadata)
     |> Deserializer.deserialize(:partitions, :map, PulsarAdmin.Model.PersistentTopicInternalStats)
  end
end

