# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.PersistentOfflineTopicStats do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :brokerName,
    :cursorDetails,
    :dataLedgerDetails,
    :messageBacklog,
    :statGeneratedAt,
    :storageSize,
    :topicName,
    :totalMessages
  ]

  @type t :: %__MODULE__{
    :brokerName => String.t | nil,
    :cursorDetails => %{optional(String.t) => PulsarAdmin.Model.CursorDetails.t} | nil,
    :dataLedgerDetails => [PulsarAdmin.Model.LedgerDetails.t] | nil,
    :messageBacklog => integer() | nil,
    :statGeneratedAt => DateTime.t | nil,
    :storageSize => integer() | nil,
    :topicName => String.t | nil,
    :totalMessages => integer() | nil
  }

  alias PulsarAdmin.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:cursorDetails, :map, PulsarAdmin.Model.CursorDetails)
     |> Deserializer.deserialize(:dataLedgerDetails, :list, PulsarAdmin.Model.LedgerDetails)
     |> Deserializer.deserialize(:statGeneratedAt, :datetime, nil)
  end
end

