# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.PersistencePolicies do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :bookkeeperAckQuorum,
    :bookkeeperEnsemble,
    :bookkeeperWriteQuorum,
    :managedLedgerMaxMarkDeleteRate
  ]

  @type t :: %__MODULE__{
    :bookkeeperAckQuorum => integer() | nil,
    :bookkeeperEnsemble => integer() | nil,
    :bookkeeperWriteQuorum => integer() | nil,
    :managedLedgerMaxMarkDeleteRate => float() | nil
  }

  def decode(value) do
    value
  end
end

