# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.PoolChunkListStats do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :chunks,
    :maxUsage,
    :minUsage
  ]

  @type t :: %__MODULE__{
    :chunks => [PulsarAdmin.Model.PoolChunkStats.t] | nil,
    :maxUsage => integer() | nil,
    :minUsage => integer() | nil
  }

  alias PulsarAdmin.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:chunks, :list, PulsarAdmin.Model.PoolChunkStats)
  end
end

