# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.PoolArenaStats do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :chunkLists,
    :numActiveAllocations,
    :numActiveHugeAllocations,
    :numActiveNormalAllocations,
    :numActiveSmallAllocations,
    :numAllocations,
    :numChunkLists,
    :numDeallocations,
    :numHugeAllocations,
    :numHugeDeallocations,
    :numNormalAllocations,
    :numNormalDeallocations,
    :numSmallAllocations,
    :numSmallDeallocations,
    :numSmallSubpages,
    :smallSubpages
  ]

  @type t :: %__MODULE__{
    :chunkLists => [PulsarAdmin.Model.PoolChunkListStats.t] | nil,
    :numActiveAllocations => integer() | nil,
    :numActiveHugeAllocations => integer() | nil,
    :numActiveNormalAllocations => integer() | nil,
    :numActiveSmallAllocations => integer() | nil,
    :numAllocations => integer() | nil,
    :numChunkLists => integer() | nil,
    :numDeallocations => integer() | nil,
    :numHugeAllocations => integer() | nil,
    :numHugeDeallocations => integer() | nil,
    :numNormalAllocations => integer() | nil,
    :numNormalDeallocations => integer() | nil,
    :numSmallAllocations => integer() | nil,
    :numSmallDeallocations => integer() | nil,
    :numSmallSubpages => integer() | nil,
    :smallSubpages => [PulsarAdmin.Model.PoolSubpageStats.t] | nil
  }

  alias PulsarAdmin.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:chunkLists, :list, PulsarAdmin.Model.PoolChunkListStats)
     |> Deserializer.deserialize(:smallSubpages, :list, PulsarAdmin.Model.PoolSubpageStats)
  end
end

