# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.PostSchemaPayload do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :properties,
    :schema,
    :type
  ]

  @type t :: %__MODULE__{
    :properties => %{optional(String.t) => String.t} | nil,
    :schema => String.t | nil,
    :type => String.t | nil
  }

  def decode(value) do
    value
  end
end

