# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.PublishRate do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :publishThrottlingRateInByte,
    :publishThrottlingRateInMsg
  ]

  @type t :: %__MODULE__{
    :publishThrottlingRateInByte => integer() | nil,
    :publishThrottlingRateInMsg => integer() | nil
  }

  def decode(value) do
    value
  end
end

