# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.PublicKey do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :algorithm,
    :encoded,
    :format
  ]

  @type t :: %__MODULE__{
    :algorithm => String.t | nil,
    :encoded => [binary()] | nil,
    :format => String.t | nil
  }

  def decode(value) do
    value
  end
end

