# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.ResetCursorData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :batchIndex,
    :entryId,
    :excluded,
    :ledgerId,
    :partitionIndex,
    :properties
  ]

  @type t :: %__MODULE__{
    :batchIndex => integer() | nil,
    :entryId => integer() | nil,
    :excluded => boolean() | nil,
    :ledgerId => integer() | nil,
    :partitionIndex => integer() | nil,
    :properties => %{optional(String.t) => String.t} | nil
  }

  def decode(value) do
    value
  end
end

