# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.ResourceDescription do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :resourceUsage,
    :usagePct
  ]

  @type t :: %__MODULE__{
    :resourceUsage => %{optional(String.t) => PulsarAdmin.Model.ResourceUsage.t} | nil,
    :usagePct => integer() | nil
  }

  alias PulsarAdmin.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:resourceUsage, :map, PulsarAdmin.Model.ResourceUsage)
  end
end

