# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.ResourceGroup do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :dispatchRateInBytes,
    :dispatchRateInMsgs,
    :publishRateInBytes,
    :publishRateInMsgs
  ]

  @type t :: %__MODULE__{
    :dispatchRateInBytes => integer() | nil,
    :dispatchRateInMsgs => integer() | nil,
    :publishRateInBytes => integer() | nil,
    :publishRateInMsgs => integer() | nil
  }

  def decode(value) do
    value
  end
end

