# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.ResourceUsage do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :limit,
    :usage
  ]

  @type t :: %__MODULE__{
    :limit => float() | nil,
    :usage => float() | nil
  }

  def decode(value) do
    value
  end
end

