# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.ResourceQuota do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :bandwidthIn,
    :bandwidthOut,
    :dynamic,
    :memory,
    :msgRateIn,
    :msgRateOut
  ]

  @type t :: %__MODULE__{
    :bandwidthIn => float() | nil,
    :bandwidthOut => float() | nil,
    :dynamic => boolean() | nil,
    :memory => float() | nil,
    :msgRateIn => float() | nil,
    :msgRateOut => float() | nil
  }

  def decode(value) do
    value
  end
end

