# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.SystemResourceUsage do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :bandwidthIn,
    :bandwidthOut,
    :cpu,
    :directMemory,
    :memory
  ]

  @type t :: %__MODULE__{
    :bandwidthIn => PulsarAdmin.Model.ResourceUsage.t | nil,
    :bandwidthOut => PulsarAdmin.Model.ResourceUsage.t | nil,
    :cpu => PulsarAdmin.Model.ResourceUsage.t | nil,
    :directMemory => PulsarAdmin.Model.ResourceUsage.t | nil,
    :memory => PulsarAdmin.Model.ResourceUsage.t | nil
  }

  alias PulsarAdmin.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:bandwidthIn, :struct, PulsarAdmin.Model.ResourceUsage)
     |> Deserializer.deserialize(:bandwidthOut, :struct, PulsarAdmin.Model.ResourceUsage)
     |> Deserializer.deserialize(:cpu, :struct, PulsarAdmin.Model.ResourceUsage)
     |> Deserializer.deserialize(:directMemory, :struct, PulsarAdmin.Model.ResourceUsage)
     |> Deserializer.deserialize(:memory, :struct, PulsarAdmin.Model.ResourceUsage)
  end
end

