# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.TopicHashPositions do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :bundle,
    :namespace,
    :topicHashPositions
  ]

  @type t :: %__MODULE__{
    :bundle => String.t | nil,
    :namespace => String.t | nil,
    :topicHashPositions => %{optional(String.t) => integer()} | nil
  }

  def decode(value) do
    value
  end
end

