# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.WorkerInfo do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :port,
    :workerHostname,
    :workerId
  ]

  @type t :: %__MODULE__{
    :port => integer() | nil,
    :workerHostname => String.t | nil,
    :workerId => String.t | nil
  }

  def decode(value) do
    value
  end
end

