# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.WorkerService do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :functions,
    :functionsV2,
    :initialized,
    :sinks,
    :sources,
    :workerConfig,
    :workers
  ]

  @type t :: %__MODULE__{
    :functions => PulsarAdmin.Model.FunctionsWorkerService.t | nil,
    :functionsV2 => PulsarAdmin.Model.FunctionsV2WorkerService.t | nil,
    :initialized => boolean() | nil,
    :sinks => PulsarAdmin.Model.SinksWorkerService.t | nil,
    :sources => PulsarAdmin.Model.SourcesWorkerService.t | nil,
    :workerConfig => PulsarAdmin.Model.WorkerConfig.t | nil,
    :workers => map() | nil
  }

  alias PulsarAdmin.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:functions, :struct, PulsarAdmin.Model.FunctionsWorkerService)
     |> Deserializer.deserialize(:functionsV2, :struct, PulsarAdmin.Model.FunctionsV2WorkerService)
     |> Deserializer.deserialize(:sinks, :struct, PulsarAdmin.Model.SinksWorkerService)
     |> Deserializer.deserialize(:sources, :struct, PulsarAdmin.Model.SourcesWorkerService)
     |> Deserializer.deserialize(:workerConfig, :struct, PulsarAdmin.Model.WorkerConfig)
  end
end

