# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Model.WorkerFunctionInstanceStats do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :metrics,
    :name
  ]

  @type t :: %__MODULE__{
    :metrics => PulsarAdmin.Model.FunctionInstanceStatsData.t | nil,
    :name => String.t | nil
  }

  alias PulsarAdmin.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:metrics, :struct, PulsarAdmin.Model.FunctionInstanceStatsData)
  end
end

