# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PulsarAdmin.Api.ResourceQuotas do
  @moduledoc """
  API calls for all endpoints tagged `ResourceQuotas`.
  """

  alias PulsarAdmin.Connection
  import PulsarAdmin.RequestBuilder

  @doc """
  Get the default quota

  ### Parameters

  - `connection` (PulsarAdmin.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%String{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec resource_quotas_get(Tesla.Env.client, keyword()) :: {:ok, nil} | {:ok, [String.t]} | {:error, Tesla.Env.t}
  def resource_quotas_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/resource-quotas")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, []},
      {403, false}
    ])
  end

  @doc """
  Set the default quota

  ### Parameters

  - `connection` (PulsarAdmin.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:body` (ResourceQuota): Default resource quota

  ### Returns

  - `{:ok, [%String{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec resource_quotas_post(Tesla.Env.client, keyword()) :: {:ok, nil} | {:ok, [String.t]} | {:error, Tesla.Env.t}
  def resource_quotas_post(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/resource-quotas")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, []},
      {403, false}
    ])
  end

  @doc """
  Remove resource quota for a namespace.

  ### Parameters

  - `connection` (PulsarAdmin.Connection): Connection to server
  - `tenant` (String.t): Tenant name
  - `namespace` (String.t): Namespace name within the specified tenant
  - `bundle` (String.t): Namespace bundle range
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec resource_quotas_tenant_namespace_bundle_delete(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def resource_quotas_tenant_namespace_bundle_delete(connection, tenant, namespace, bundle, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/resource-quotas/#{tenant}/#{namespace}/#{bundle}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {307, false},
      {403, false},
      {409, false}
    ])
  end

  @doc """
  Get resource quota of a namespace bundle.

  ### Parameters

  - `connection` (PulsarAdmin.Connection): Connection to server
  - `tenant` (String.t): Tenant name
  - `namespace` (String.t): Namespace name within the specified tenant
  - `bundle` (String.t): Namespace bundle range
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, PulsarAdmin.Model.ResourceQuota.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec resource_quotas_tenant_namespace_bundle_get(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, nil} | {:ok, PulsarAdmin.Model.ResourceQuota.t} | {:error, Tesla.Env.t}
  def resource_quotas_tenant_namespace_bundle_get(connection, tenant, namespace, bundle, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/resource-quotas/#{tenant}/#{namespace}/#{bundle}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, PulsarAdmin.Model.ResourceQuota},
      {307, false},
      {403, false},
      {404, false}
    ])
  end

  @doc """
  Set resource quota on a namespace.

  ### Parameters

  - `connection` (PulsarAdmin.Connection): Connection to server
  - `tenant` (String.t): Tenant name
  - `namespace` (String.t): Namespace name within the specified tenant
  - `bundle` (String.t): Namespace bundle range
  - `opts` (keyword): Optional parameters
    - `:body` (ResourceQuota): Resource quota for the specified namespace

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec resource_quotas_tenant_namespace_bundle_post(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def resource_quotas_tenant_namespace_bundle_post(connection, tenant, namespace, bundle, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/resource-quotas/#{tenant}/#{namespace}/#{bundle}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {307, false},
      {403, false},
      {409, false}
    ])
  end
end
